version: '3'
 
services:
  app:
    image: ${DOCKER_IMAGE_COMPOSE}
    container_name: ${DOCKER_CONTAINER_NAME}
    expose:
      - "5000"
    environment:
      APP_DB_SECRET: /app/db-secret
      APP_DW_SECRET: /app/dw-secret
    volumes:
      - ~/Projects/secrets/blocket-secret:/app/db-secret
      - ~/Projects/secrets/db-secret-dev:/app/dw-secret
