- defaultTab: nodes
  description: |-
        Github: https://github.mpi-internal.com/Yapo/data-revenues \
        Retrieves stored purchases from blocketDb and store them in dwh \
        sudo docker run --rm -v /home/bnbiuser/secrets/blocket_db:/app/db-blocket \
                        -v /home/bnbiuser/secrets/dw_db:/app/db-secret \
                        -e APP_BLOCKET_SECRET=/app/db-blocket \
                        -e APP_DB_SECRET=/app/db-secret \
                        containers.mpi-internal.com/yapo/store-purchase:latest
  executionEnabled: true
  group: DOCKER/REVENUES
  loglevel: DEBUG
  name: Revenues - Store Purchases
  nodeFilterEditable: false
  nodefilters:
    dispatch:
      excludePrecedence: true
      keepgoing: false
      rankOrder: ascending
      successOnEmptyNodeFilter: false
      threadcount: '1'
    filter: 'name: dockerhost'
  nodesSelectedByDefault: true
  notification:
    onfailure:
      email:
        recipients: data_team@adevinta.com
        subject: ${job.execid} ${execution.status} ${job.name} - Fallo definitivo
    onretryablefailure:
      email:
        recipients: data_team@adevinta.com
        subject: ${job.execid} ${execution.status} ${job.name} - Fallo por reintento
  notifyAvgDurationThreshold: null
  schedule:
    month: '*'
    time:
      hour: '0'
      minute: '10'
      seconds: '0'
    weekday:
      day: '*'
    year: '*'
  retry:
    retry: 3
    delay: 20m
  scheduleEnabled: true
  sequence:
    commands:
    - script: |-
        sudo docker pull containers.mpi-internal.com/yapo/store-purchase:latest
        sudo docker run --rm -v /home/bnbiuser/secrets/blocket_db:/app/db-blocket \
                        -v /home/bnbiuser/secrets/dw_db:/app/db-secret \
                        -e APP_BLOCKET_SECRET=/app/db-blocket \
                        -e APP_DB_SECRET=/app/db-secret \
                        containers.mpi-internal.com/yapo/store-purchase:latest
    keepgoing: false
    strategy: node-first
  timeZone: America/Santiago
